name: "Phanalist GitHub action."
on:
  push:
    branches:
      - "main"
jobs:
  phanalist:
    runs-on: "linux"
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Run phanalst.
      uses: denzyldick/phanalist-action@0.1
      with:
        src: "./vendor"
