name: "Phanalist GitHub action."
on:
  push:
    branches:
      - "master"
jobs:
  install-phanalist:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  uses: denzyldick/phanalist-action@v0.0.1
         with:
           src: /app
