name: "Phanalist GitHub action."
on:
  push:
    branches:
      - "master"
jobs:
  install-phanalist:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denzyldick/phanalist-action@v0.1.23
        with:
          src: /app
