name: "Phanalist GitHub action."
on:
  push:
    branches:
      - "master"
jobs:
  phanalist:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Run phanalst.
      uses: denzyldick/phanalist-action@v0.0.1
      with:
        src: "./app"
